/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.Toolkit;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.net.URLDecoder;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import static main.function.lc2;
import org.apache.commons.net.ftp.FTP;
import org.apache.commons.net.ftp.FTPClient;
import org.apache.commons.net.ftp.FTPReply;
/**
 *
 * @author trinhdangmau
 */
public class dashboard extends javax.swing.JFrame {

    /**
     * Creates new form dashboard
     */
    public dashboard() {
        initComponents();
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cmd_customer = new javax.swing.JButton();
        cmd_parner = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        cmd_export = new javax.swing.JButton();
        cmd_export_list = new javax.swing.JButton();
        cmd_employee = new javax.swing.JButton();
        cmd_dept_customer = new javax.swing.JButton();
        cmd_import = new javax.swing.JButton();
        cmd_import_list = new javax.swing.JButton();
        cmd_order = new javax.swing.JButton();
        cmd_order_list = new javax.swing.JButton();
        cmd_order_list1 = new javax.swing.JButton();
        lable_user = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        menu_backup = new javax.swing.JMenuItem();
        menu_restore_database = new javax.swing.JMenuItem();
        cmdm_exit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menu_employee = new javax.swing.JMenuItem();
        menu_customer = new javax.swing.JMenuItem();
        menu_partner = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        menu_import = new javax.swing.JMenuItem();
        menu_import_list = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        menu_export = new javax.swing.JMenuItem();
        menu_export_list = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        menu_order = new javax.swing.JMenuItem();
        menu_order_list = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menu_sync = new javax.swing.JMenuItem();
        cmd_setting = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menu_test_frame = new javax.swing.JMenuItem();
        menu_update = new javax.swing.JMenuItem();
        menu_aboutus = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("AnThaiPhuSteel Co., Ltd.");

        cmd_customer.setText("Quản lý khách hàng");
        cmd_customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_customerActionPerformed(evt);
            }
        });

        cmd_parner.setText("Quản lý đối tác");
        cmd_parner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_parnerActionPerformed(evt);
            }
        });

        jButton1.setText("Quản lý Sản Phẩm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cmd_export.setText("Quản lý Xuất hàng");
        cmd_export.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_exportActionPerformed(evt);
            }
        });

        cmd_export_list.setText("Danh sách xuất");
        cmd_export_list.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_export_listActionPerformed(evt);
            }
        });

        cmd_employee.setText("Quản lý Nhân Viên");
        cmd_employee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_employeeActionPerformed(evt);
            }
        });

        cmd_dept_customer.setText("Công Nợ KH");
        cmd_dept_customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_dept_customerActionPerformed(evt);
            }
        });

        cmd_import.setText("Quản lý Nhập hàng");
        cmd_import.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_importActionPerformed(evt);
            }
        });

        cmd_import_list.setText("Danh sách nhập");
        cmd_import_list.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_import_listActionPerformed(evt);
            }
        });

        cmd_order.setText("Quản lý đặt hàng");
        cmd_order.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_orderActionPerformed(evt);
            }
        });

        cmd_order_list.setText("DS đặt hàng");
        cmd_order_list.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_order_listActionPerformed(evt);
            }
        });

        cmd_order_list1.setText("Báo giá");
        cmd_order_list1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_order_list1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cmd_customer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmd_parner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(cmd_employee, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmd_order_list1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cmd_import_list, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmd_order_list, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmd_dept_customer, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmd_export_list, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cmd_import, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmd_order, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmd_export, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cmd_import, cmd_import_list});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cmd_dept_customer, cmd_export, cmd_export_list});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmd_customer, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmd_import)
                    .addComponent(cmd_export)
                    .addComponent(cmd_order, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmd_export_list, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmd_parner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmd_import_list, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmd_order_list, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmd_dept_customer, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmd_employee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmd_order_list1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cmd_customer, cmd_employee, cmd_export, cmd_import, cmd_import_list, cmd_parner, jButton1});

        lable_user.setText("+(user)");

        jLabel1.setText("Bạn đang đăng nhập dưới tên người dùng :");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(222, 68, 0));
        jLabel2.setText("Hệ Thống Quản Lý Kinh Doanh");

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 99, 8));
        jLabel3.setText("An Thái Phú Steel Co., Ltd.");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/database/logo90.png"))); // NOI18N

        jMenu1.setText("File");

        jMenuItem1.setText("Tạo mới Database");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        menu_backup.setText("Sao lưu cơ sở dữ liệu");
        menu_backup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_backupActionPerformed(evt);
            }
        });
        jMenu1.add(menu_backup);

        menu_restore_database.setText("Phục hồi cơ sở dữ liệu");
        menu_restore_database.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_restore_databaseActionPerformed(evt);
            }
        });
        jMenu1.add(menu_restore_database);

        cmdm_exit.setText("Thoát");
        cmdm_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdm_exitActionPerformed(evt);
            }
        });
        jMenu1.add(cmdm_exit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Nhân lực");

        menu_employee.setText("Quản lý nhân viên");
        menu_employee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_employeeActionPerformed(evt);
            }
        });
        jMenu2.add(menu_employee);

        menu_customer.setText("Quản lý khách hàng");
        menu_customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_customerActionPerformed(evt);
            }
        });
        jMenu2.add(menu_customer);

        menu_partner.setText("Quản lý đối tác");
        menu_partner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_partnerActionPerformed(evt);
            }
        });
        jMenu2.add(menu_partner);

        jMenuBar1.add(jMenu2);

        jMenu7.setText("Nhập hàng");

        menu_import.setText("Quản lý nhập hàng");
        menu_import.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_importActionPerformed(evt);
            }
        });
        jMenu7.add(menu_import);

        menu_import_list.setText("Danh sách nhập hàng");
        menu_import_list.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_import_listActionPerformed(evt);
            }
        });
        jMenu7.add(menu_import_list);

        jMenuBar1.add(jMenu7);

        jMenu8.setText("Xuất hàng");

        menu_export.setText("Quản lý xuất hàng");
        menu_export.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_exportActionPerformed(evt);
            }
        });
        jMenu8.add(menu_export);

        menu_export_list.setText("Danh sách xuất hàng");
        menu_export_list.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_export_listActionPerformed(evt);
            }
        });
        jMenu8.add(menu_export_list);

        jMenuBar1.add(jMenu8);

        jMenu9.setText("Đặt hàng");

        menu_order.setText("Đặt hàng mới");
        menu_order.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_orderActionPerformed(evt);
            }
        });
        jMenu9.add(menu_order);

        menu_order_list.setText("Danh sách đặt hàng");
        menu_order_list.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_order_listActionPerformed(evt);
            }
        });
        jMenu9.add(menu_order_list);

        jMenuBar1.add(jMenu9);

        jMenu3.setText("Tools");

        menu_sync.setText("Sync");
        menu_sync.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_syncActionPerformed(evt);
            }
        });
        jMenu3.add(menu_sync);

        cmd_setting.setText("Cài đặt");
        cmd_setting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_settingActionPerformed(evt);
            }
        });
        jMenu3.add(cmd_setting);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Help");

        menu_test_frame.setText("test_frame");
        menu_test_frame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_test_frameActionPerformed(evt);
            }
        });
        jMenu4.add(menu_test_frame);

        menu_update.setText("Check update");
        menu_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_updateActionPerformed(evt);
            }
        });
        jMenu4.add(menu_update);

        menu_aboutus.setText("About us");
        menu_aboutus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_aboutusActionPerformed(evt);
            }
        });
        jMenu4.add(menu_aboutus);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lable_user, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lable_user))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void setIcon() {
        String purl = lc2();
        String Url = purl+"/database/logo90.png";
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(Url));
    }
    
    private void cmd_customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_customerActionPerformed
        new add_customer_frame().setVisible(true);
    }//GEN-LAST:event_cmd_customerActionPerformed

    private void cmd_parnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_parnerActionPerformed
        new partner_frame().setVisible(true);
    }//GEN-LAST:event_cmd_parnerActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new product_frame().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cmd_exportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_exportActionPerformed
        new export_frame().setVisible(true);
    }//GEN-LAST:event_cmd_exportActionPerformed

    private void cmdm_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdm_exitActionPerformed
        Logrecord.log_out();
        System.exit(0);
    }//GEN-LAST:event_cmdm_exitActionPerformed

    private void cmd_settingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_settingActionPerformed
        new setting_frame().setVisible(true);
    }//GEN-LAST:event_cmd_settingActionPerformed

    private void cmd_export_listActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_export_listActionPerformed
        new export_list_frame().setVisible(true);
    }//GEN-LAST:event_cmd_export_listActionPerformed

    private void cmd_employeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_employeeActionPerformed
        new employee_frame().setVisible(true);
    }//GEN-LAST:event_cmd_employeeActionPerformed

    private void cmd_dept_customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_dept_customerActionPerformed
        new debt_cust_frame().setVisible(true);
    }//GEN-LAST:event_cmd_dept_customerActionPerformed

    private void cmd_importActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_importActionPerformed
        new import_frame().setVisible(true);
    }//GEN-LAST:event_cmd_importActionPerformed

    private void menu_backupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_backupActionPerformed
      
        //encrypt
        String timeStamp = new SimpleDateFormat("yyyyMMdd_HHmmss").format(Calendar.getInstance().getTime());
        String MCH = function.MCH();
        String outputFile = MCH+"_"+timeStamp+".atp";
        String out = "backup/" + outputFile;
        backupdata.databk(out);
        
    }//GEN-LAST:event_menu_backupActionPerformed
    
    private void menu_syncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_syncActionPerformed
        //new sync_status_frame().setVisible(true);
        JOptionPane.showMessageDialog(null, "Function is updating!");
    }//GEN-LAST:event_menu_syncActionPerformed

    private void menu_aboutusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_aboutusActionPerformed
        new aboutus_frame().setVisible(true);
    }//GEN-LAST:event_menu_aboutusActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new create_data_frame().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void menu_test_frameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_test_frameActionPerformed
        JOptionPane.showMessageDialog(null, "Function is updating!");//new test().setVisible(true);
    }//GEN-LAST:event_menu_test_frameActionPerformed

    private void menu_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_updateActionPerformed
        try {
            Runtime.getRuntime().exec("update.bat");
            Logrecord.log_out();
            System.exit(0);
        } catch (IOException ex) {
            Logger.getLogger(dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menu_updateActionPerformed

    private void cmd_import_listActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_import_listActionPerformed
        new import_list_frame().setVisible(true);
    }//GEN-LAST:event_cmd_import_listActionPerformed

    private void menu_restore_databaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_restore_databaseActionPerformed
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("anthaiphu", "atp");
        chooser.setFileFilter(filter);
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String outfile = function.currentdata();
        File decryptedFile = new File(outfile);
        File backup = new File(function.lc2()+"/database/bak.db");
        decryptedFile.renameTo(backup);
        try {
            CryptoUtils.decrypt("QA562002", f, decryptedFile);
        } catch (CryptoException ex) {
            System.out.println(ex.getMessage());
            ex.printStackTrace();
        }
        JOptionPane.showMessageDialog(null, "Phục hồi thành công!");
    }//GEN-LAST:event_menu_restore_databaseActionPerformed

    private void cmd_orderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_orderActionPerformed
        new order_form().setVisible(true);
    }//GEN-LAST:event_cmd_orderActionPerformed

    private void cmd_order_listActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_order_listActionPerformed
        new order_list_frame().setVisible(true);
    }//GEN-LAST:event_cmd_order_listActionPerformed

    private void cmd_order_list1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_order_list1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmd_order_list1ActionPerformed

    private void menu_employeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_employeeActionPerformed
        new employee_frame().setVisible(true);
    }//GEN-LAST:event_menu_employeeActionPerformed

    private void menu_partnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_partnerActionPerformed
        new partner_frame().setVisible(true);
    }//GEN-LAST:event_menu_partnerActionPerformed

    private void menu_customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_customerActionPerformed
        new add_customer_frame().setVisible(true);
    }//GEN-LAST:event_menu_customerActionPerformed

    private void menu_importActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_importActionPerformed
        new import_frame().setVisible(true);
    }//GEN-LAST:event_menu_importActionPerformed

    private void menu_import_listActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_import_listActionPerformed
        new import_list_frame().setVisible(true);
    }//GEN-LAST:event_menu_import_listActionPerformed

    private void menu_orderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_orderActionPerformed
        new order_form().setVisible(true);
    }//GEN-LAST:event_menu_orderActionPerformed

    private void menu_order_listActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_order_listActionPerformed
        new order_list_frame().setVisible(true);
    }//GEN-LAST:event_menu_order_listActionPerformed

    private void menu_exportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_exportActionPerformed
        new export_frame().setVisible(true);
    }//GEN-LAST:event_menu_exportActionPerformed

    private void menu_export_listActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_export_listActionPerformed
        new export_list_frame().setVisible(true);
    }//GEN-LAST:event_menu_export_listActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmd_customer;
    private javax.swing.JButton cmd_dept_customer;
    private javax.swing.JButton cmd_employee;
    private javax.swing.JButton cmd_export;
    private javax.swing.JButton cmd_export_list;
    private javax.swing.JButton cmd_import;
    private javax.swing.JButton cmd_import_list;
    private javax.swing.JButton cmd_order;
    private javax.swing.JButton cmd_order_list;
    private javax.swing.JButton cmd_order_list1;
    private javax.swing.JButton cmd_parner;
    private javax.swing.JMenuItem cmd_setting;
    private javax.swing.JMenuItem cmdm_exit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel lable_user;
    private javax.swing.JMenuItem menu_aboutus;
    private javax.swing.JMenuItem menu_backup;
    private javax.swing.JMenuItem menu_customer;
    private javax.swing.JMenuItem menu_employee;
    private javax.swing.JMenuItem menu_export;
    private javax.swing.JMenuItem menu_export_list;
    private javax.swing.JMenuItem menu_import;
    private javax.swing.JMenuItem menu_import_list;
    private javax.swing.JMenuItem menu_order;
    private javax.swing.JMenuItem menu_order_list;
    private javax.swing.JMenuItem menu_partner;
    private javax.swing.JMenuItem menu_restore_database;
    private javax.swing.JMenuItem menu_sync;
    private javax.swing.JMenuItem menu_test_frame;
    private javax.swing.JMenuItem menu_update;
    // End of variables declaration//GEN-END:variables
}
