/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import net.proteanit.sql.DbUtils;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperPrintManager;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author dmautrinh
 */
public class order_list_frame extends javax.swing.JFrame {
    Connection conn=null;
    ResultSet rs =null;
    PreparedStatement pst =null;
    /**
     * Creates new form order_list_frame
     */
    public order_list_frame() {
        initComponents();
        conn=javaconnect.ConnecrDb();
        update_table();
        setIcon();
        Update_tbl_order_detail("null");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmd_delete = new javax.swing.JButton();
        cmd_print_preview = new javax.swing.JButton();
        cmd_print = new javax.swing.JButton();
        cmd_close = new javax.swing.JButton();
        txt_search = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_order_list = new javax.swing.JTable();
        cmd_addnew = new javax.swing.JButton();
        cmd_open_change = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_order_detail = new javax.swing.JTable();
        lable_no_product = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menu_close = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        cmd_delete.setText("Xóa");
        cmd_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_deleteActionPerformed(evt);
            }
        });

        cmd_print_preview.setText("Print Preview");
        cmd_print_preview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_print_previewActionPerformed(evt);
            }
        });

        cmd_print.setText("Print");
        cmd_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_printActionPerformed(evt);
            }
        });

        cmd_close.setText("Đóng");
        cmd_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_closeActionPerformed(evt);
            }
        });

        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
        });

        tbl_order_list.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_order_list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_order_listMouseClicked(evt);
            }
        });
        tbl_order_list.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbl_order_listKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_order_list);

        cmd_addnew.setText("Thêm mới");
        cmd_addnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_addnewActionPerformed(evt);
            }
        });

        cmd_open_change.setText("Mở/thay đổi");
        cmd_open_change.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_open_changeActionPerformed(evt);
            }
        });

        tbl_order_detail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbl_order_detail);

        lable_no_product.setText("+(No. product)");

        jMenu1.setText("File");

        menu_close.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
        menu_close.setText("Close");
        menu_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_closeActionPerformed(evt);
            }
        });
        jMenu1.add(menu_close);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 703, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(cmd_addnew)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmd_open_change)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmd_print_preview)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmd_print, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmd_delete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmd_close)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lable_no_product, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cmd_addnew, cmd_close, cmd_delete, cmd_open_change, cmd_print, cmd_print_preview});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lable_no_product)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmd_addnew)
                    .addComponent(cmd_open_change)
                    .addComponent(cmd_delete)
                    .addComponent(cmd_close)
                    .addComponent(cmd_print_preview)
                    .addComponent(cmd_print))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void setIcon() {
        String purl = function.lc2();
        String Url = purl+"/database/logo90.png";
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(Url));
    }

    private void update_table(){
    try{
        String sql = "SELECT code_or AS 'ID', name_cust As 'Tên KH', date_or AS 'Ngày đặt', "
                + "date_delivery_or AS 'Ngày giao', status_or AS 'Trạng thái' "
                    + "FROM order_tb LEFT JOIN customer on code_cust_or = code_cust ORDER BY date_or DESC";

            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            tbl_order_list.setModel(DbUtils.resultSetToTableModel(rs));
            DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
            rightRenderer.setHorizontalAlignment( JLabel.RIGHT );
            tbl_order_list.getColumnModel().getColumn(2).setCellRenderer( rightRenderer );
            tbl_order_list.getColumnModel().getColumn(3).setCellRenderer( rightRenderer );
            tbl_order_list.getColumnModel().getColumn(4).setCellRenderer( rightRenderer );
        }catch (Exception e){JOptionPane.showMessageDialog(null, e); }
        finally { try { rs.close(); pst.close();}catch (Exception e){  } }
    }
    
    public void Update_tbl_order_detail(String code){
    //String tmp = txt_code_or.getText().toUpperCase();
        
        if(code.equals("null")){
            String sql = "SELECT code_ordt AS 'ID', name_prod AS 'Tên SP', specification_ordt AS 'Quy cách', "
                + "no_ordt AS 'No.', eweight_ordt AS 'TL ước tính', unit_ordt AS 'Unit', "
                + "price_ordt AS 'Đơn giá', monetize_ordt AS 'Thành tiền'"
                + "FROM order_detail "
                + "LEFT JOIN product_information ON code_prod_ordt = code_prod ";
            String sql1="SELECT count(code_ordt) FROM order_detail ";
            
            try{
                pst=conn.prepareStatement(sql);
                rs=pst.executeQuery();
                tbl_order_detail.setModel(DbUtils.resultSetToTableModel(rs));
                tbl_order_detail.getColumnModel().getColumn(3).setPreferredWidth(12);
                tbl_order_detail.getColumnModel().getColumn(1).setPreferredWidth(30);
                tbl_order_detail.getColumnModel().getColumn(5).setPreferredWidth(12);
                        }
                catch (Exception e){JOptionPane.showMessageDialog(null, e);}
                finally {try {rs.close(); pst.close();}catch (Exception e){}}

            try {

                   pst =conn.prepareStatement(sql1);
                   rs =pst.executeQuery();

                   if (rs.next()){
                       String count = rs.getString("count(code_ordt)");
                       lable_no_product.setText("No. :"+count);
                   }
                }catch (Exception e){JOptionPane.showMessageDialog(null, e); }
                    finally { try { rs.close(); pst.close();}catch (Exception e){  } }
    
        }else{
            String sql = "SELECT code_ordt AS 'ID', name_prod AS 'Tên SP', specification_ordt AS 'Quy cách', "
                + "no_ordt AS 'No.', eweight_ordt AS 'TL ước tính', unit_ordt AS 'Unit', "
                + "price_ordt AS 'Đơn giá', monetize_ordt AS 'Thành tiền'"
                + "FROM order_detail "
                + "LEFT JOIN product_information ON code_prod_ordt = code_prod "
                + "WHERE code_or_ordt = '"+code+"' ";
            String sql1="SELECT count(code_ordt) FROM order_detail WHERE code_or_ordt ='"+code+"' ";
            try{
                pst=conn.prepareStatement(sql);
                rs=pst.executeQuery();
                tbl_order_detail.setModel(DbUtils.resultSetToTableModel(rs));
                tbl_order_detail.getColumnModel().getColumn(3).setPreferredWidth(12);
                tbl_order_detail.getColumnModel().getColumn(1).setPreferredWidth(30);
                tbl_order_detail.getColumnModel().getColumn(5).setPreferredWidth(12);
                        }
                catch (Exception e){JOptionPane.showMessageDialog(null, e);}
                finally {try {rs.close(); pst.close();}catch (Exception e){}}

            try {

                   pst =conn.prepareStatement(sql1);
                   rs =pst.executeQuery();

                   if (rs.next()){
                       String count = rs.getString("count(code_ordt)");
                       lable_no_product.setText("No. :"+count);
                   }
                }catch (Exception e){JOptionPane.showMessageDialog(null, e); }
                    finally { try { rs.close(); pst.close();}catch (Exception e){  } }
        }
    
    }
    
    private void cmd_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_deleteActionPerformed
        int p =JOptionPane.showConfirmDialog(null, "Bạn có muốn xóa dữ liệu Đơn Hàng này không? \nDữ liệu sản phẩm trong đơn hàng sẻ được xóa theo", "Xóa Đơn hàng", JOptionPane.YES_NO_OPTION);
        if (p==0){
            int row=tbl_order_list.getSelectedRow();
            String Table_click=(tbl_order_list.getModel().getValueAt(row, 0).toString());
            try{
                String sql="DELETE FROM order_detail where code_or_ordt = ?";
                pst=conn.prepareStatement(sql);
                pst.setString(1, Table_click);
                pst.execute();
            }catch(Exception e){JOptionPane.showMessageDialog(null, e);}
            finally {try {rs.close();pst.close();}catch (Exception e){}}

            try{
                String sql="DELETE FROM order_tb where code_or = ?";
                pst=conn.prepareStatement(sql);
                pst.setString(1, Table_click);
                pst.execute();
            }catch(Exception e){JOptionPane.showMessageDialog(null, e);}
            finally {try {rs.close();pst.close();}catch (Exception e){}}
        }
        update_table();
    }//GEN-LAST:event_cmd_deleteActionPerformed

    private void cmd_print_previewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_print_previewActionPerformed

        int row=tbl_order_list.getSelectedRow();
        String code_or=(tbl_order_list.getModel().getValueAt(row, 0).toString());
        try {
            JasperDesign jd=JRXmlLoader.load(getClass().getResourceAsStream("order_print.jrxml"));
            String sql = "SELECT * FROM order_tb "
                    + "LEFT JOIN order_detail ON code_or = code_or_ordt "
                    + "LEFT JOIN product_information ON code_prod_ordt = code_prod "
                    + "WHERE code_or = '" + code_or+"'";
            JRDesignQuery newQuery= new JRDesignQuery();
            newQuery.setText(sql);
            jd.setQuery(newQuery);

            JasperReport jr=JasperCompileManager.compileReport(jd);
            JasperPrint jp=JasperFillManager.fillReport(jr, null, conn);
            JasperViewer jv = new JasperViewer(jp,false);
            jv.setVisible(true);
            //JasperPrintManager.printReport(jp,true);;

        } catch (JRException ex) {
            Logger.getLogger(test.class.getName()).log(Level.SEVERE, null, ex);
        }finally {try {rs.close();pst.close();}catch (Exception e){}}
    }//GEN-LAST:event_cmd_print_previewActionPerformed

    private void cmd_printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_printActionPerformed
        int row=tbl_order_list.getSelectedRow();
        String code_or=(tbl_order_list.getModel().getValueAt(row, 0).toString());
        try {
            JasperDesign jd=JRXmlLoader.load(getClass().getResourceAsStream("order_print.jrxml"));
            String sql = "SELECT * FROM order_tb "
                    + "LEFT JOIN order_detail ON code_or = code_or_ordt "
                    + "LEFT JOIN product_information ON code_prod_ordt = code_prod "
                    + "WHERE code_or = '" + code_or+"'";
            JRDesignQuery newQuery= new JRDesignQuery();
            newQuery.setText(sql);
            jd.setQuery(newQuery);

            JasperReport jr=JasperCompileManager.compileReport(jd);
            JasperPrint jp=JasperFillManager.fillReport(jr, null, conn);
            //JasperViewer jv = new JasperViewer(jp,false);
            //jv.setVisible(true);
            JasperPrintManager.printReport(jp,true);

        } catch (JRException ex) {
            Logger.getLogger(test.class.getName()).log(Level.SEVERE, null, ex);
        }finally {try {rs.close();pst.close();}catch (Exception e){}}
    }//GEN-LAST:event_cmd_printActionPerformed

    private void cmd_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_closeActionPerformed
        try {rs.close();pst.close();dispose();}catch (Exception e){}
    }//GEN-LAST:event_cmd_closeActionPerformed

    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased
        String search = "%"+txt_search.getText() + "%";

        String sql = "SELECT code_or AS 'ID', name_cust As 'Tên KH', date_or AS 'Ngày đặt', "
                + "date_delivery_or AS 'Ngày giao', status_or AS 'Trạng thái' "
                + "FROM order_tb LEFT JOIN customer on code_cust_or = code_cust  "
                + "WHERE (code_or || name_cust || province_cust || date_or || date_delivery_or || status_or) LIKE '"+search+"' ORDER BY date_or DESC  ";
        try{
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            tbl_order_list.setModel(DbUtils.resultSetToTableModel(rs));
            DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
            rightRenderer.setHorizontalAlignment( JLabel.RIGHT );
            tbl_order_list.getColumnModel().getColumn(2).setCellRenderer( rightRenderer );
            tbl_order_list.getColumnModel().getColumn(3).setCellRenderer( rightRenderer );
            tbl_order_list.getColumnModel().getColumn(4).setCellRenderer( rightRenderer );
        }
        catch (Exception e){JOptionPane.showMessageDialog(null, e);}
        finally {try {rs.close(); pst.close();}catch (Exception e){}}
    }//GEN-LAST:event_txt_searchKeyReleased

    private void cmd_addnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_addnewActionPerformed
        new order_form().setVisible(true);
    }//GEN-LAST:event_cmd_addnewActionPerformed

    private void cmd_open_changeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_open_changeActionPerformed
        order_form order = new order_form();
        int row=tbl_order_list.getSelectedRow();
        String code_or=(tbl_order_list.getModel().getValueAt(row, 0).toString());
        order_form.txt_code_or.setText(code_or);
        order.setVisible(true);
    }//GEN-LAST:event_cmd_open_changeActionPerformed

    private void menu_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_closeActionPerformed
        try {rs.close();pst.close();dispose();}catch (Exception e){}
    }//GEN-LAST:event_menu_closeActionPerformed

    private void tbl_order_listKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbl_order_listKeyPressed
        int row=tbl_order_list.getSelectedRow();
        String Table_click=(tbl_order_list.getModel().getValueAt(row, 0).toString());
        Update_tbl_order_detail(Table_click);
    }//GEN-LAST:event_tbl_order_listKeyPressed

    private void tbl_order_listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_order_listMouseClicked
        int row=tbl_order_list.getSelectedRow();
        String Table_click=(tbl_order_list.getModel().getValueAt(row, 0).toString());
        Update_tbl_order_detail(Table_click);
    }//GEN-LAST:event_tbl_order_listMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(order_list_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(order_list_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(order_list_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(order_list_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new order_list_frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmd_addnew;
    private javax.swing.JButton cmd_close;
    private javax.swing.JButton cmd_delete;
    private javax.swing.JButton cmd_open_change;
    private javax.swing.JButton cmd_print;
    private javax.swing.JButton cmd_print_preview;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lable_no_product;
    private javax.swing.JMenuItem menu_close;
    private javax.swing.JTable tbl_order_detail;
    private javax.swing.JTable tbl_order_list;
    private javax.swing.JTextField txt_search;
    // End of variables declaration//GEN-END:variables
}
