/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.Cursor;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import static main.function.MCH;
import static main.function.lc2;
import net.proteanit.sql.DbUtils;
import org.apache.poi.hssf.usermodel.HSSFCellStyle;
import org.apache.poi.hssf.usermodel.HSSFFont;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;

/**
 *
 * @author trinhdangmau
 */
public class partner_frame extends javax.swing.JFrame {
    Connection conn=null;
    ResultSet rs =null;
    PreparedStatement pst =null;

    /**
     * Creates new form partner_frame
     */
    public partner_frame() {
        initComponents();
        conn=javaconnect.ConnecrDb();
        Update_table_partner();
        setIcon();
    }

    private void setIcon() {
        String purl = lc2();
        String Url = purl+"/database/logo90.png";
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(Url));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_partner = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txt_company_part = new javax.swing.JTextField();
        txt_email_part = new javax.swing.JTextField();
        txt_name_part = new javax.swing.JTextField();
        txt_note_part = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_phone_part = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_code_part = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_add_part = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_district_part = new javax.swing.JTextField();
        txt_province_part = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_fax_part = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_total_part = new javax.swing.JLabel();
        cmd_close = new javax.swing.JButton();
        cmd_addnew = new javax.swing.JButton();
        cmd_save = new javax.swing.JButton();
        cmd_delete = new javax.swing.JButton();
        cmd_update = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        cmd_mclose = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        cmd_refreshtable = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menu_export_xls = new javax.swing.JMenuItem();
        menu_export_csv = new javax.swing.JMenuItem();
        menu_import_csv = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        menu_delete_all = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Đối tác");

        tbl_partner.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_partner.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_partnerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_partner);

        jLabel4.setText("Quận/huyện :");

        jLabel1.setText("ID Đối tác : ");

        jLabel3.setText("Địa chỉ :");

        jLabel9.setText("Địa chỉ Email :");

        jLabel2.setText("Họ và Tên :");

        jLabel7.setText("Số điện thoại :");

        jLabel6.setText("Công Ty :");

        jLabel5.setText("Tỉnh/Thành phố :");

        jLabel8.setText("Số Fax : ");

        jLabel10.setText("Ghi Chú :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txt_email_part, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_fax_part, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_phone_part, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_company_part, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_province_part, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_district_part, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_add_part, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_name_part, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_code_part, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_note_part, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_code_part, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_name_part, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_add_part, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_district_part, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_province_part, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_company_part, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_phone_part, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_fax_part, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txt_email_part, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txt_note_part, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        txt_total_part.setText("+total");

        cmd_close.setText(" Đóng");
        cmd_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_closeActionPerformed(evt);
            }
        });

        cmd_addnew.setText("Thêm mới");
        cmd_addnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_addnewActionPerformed(evt);
            }
        });

        cmd_save.setText("Lưu");
        cmd_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_saveActionPerformed(evt);
            }
        });

        cmd_delete.setText("Xóa");
        cmd_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_deleteActionPerformed(evt);
            }
        });

        cmd_update.setText("Update");
        cmd_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_updateActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel11.setText("Quản lý Đối Tác");

        jMenu1.setText("File");

        cmd_mclose.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
        cmd_mclose.setText("Close");
        cmd_mclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_mcloseActionPerformed(evt);
            }
        });
        jMenu1.add(cmd_mclose);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        cmd_refreshtable.setText("Refresh table");
        cmd_refreshtable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_refreshtableActionPerformed(evt);
            }
        });
        jMenu2.add(cmd_refreshtable);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Tools");

        menu_export_xls.setText("Export to .xls");
        menu_export_xls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_export_xlsActionPerformed(evt);
            }
        });
        jMenu3.add(menu_export_xls);

        menu_export_csv.setText("Export to .csv");
        menu_export_csv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_export_csvActionPerformed(evt);
            }
        });
        jMenu3.add(menu_export_csv);

        menu_import_csv.setText("Import from .csv");
        menu_import_csv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_import_csvActionPerformed(evt);
            }
        });
        jMenu3.add(menu_import_csv);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Search");
        jMenuBar1.add(jMenu4);

        jMenu6.setText("Advance");

        menu_delete_all.setText("Delete All");
        menu_delete_all.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_delete_allActionPerformed(evt);
            }
        });
        jMenu6.add(menu_delete_all);

        jMenuBar1.add(jMenu6);

        jMenu5.setText("Help");
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmd_addnew)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmd_save, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cmd_update, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmd_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmd_close, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_total_part, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(txt_total_part)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmd_addnew)
                            .addComponent(cmd_save)
                            .addComponent(cmd_delete))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmd_close)
                            .addComponent(cmd_update))
                        .addGap(20, 20, 20))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
private void Update_table_partner(){
        try{
        String sql = "SELECT code_part AS 'ID', name_part AS 'Họ tên', phone_part AS 'Phone' FROM partner ORDER BY code_part";
        pst=conn.prepareStatement(sql);
        rs=pst.executeQuery();
        tbl_partner.setModel(DbUtils.resultSetToTableModel(rs));
        tbl_partner.getColumnModel().getColumn(0).setPreferredWidth(12);
                }
        catch (Exception e){JOptionPane.showMessageDialog(null, e);}
        finally {try {rs.close(); pst.close();}catch (Exception e){}}
    
    try {
        String sql1="SELECT count(code_part) FROM partner ";
           pst =conn.prepareStatement(sql1);
           rs =pst.executeQuery();
           
           if (rs.next()){
               String count = rs.getString("count(code_part)");
               txt_total_part.setText("Tổng số lượng khách hàng là:"+count);
           }
        }catch (Exception e){JOptionPane.showMessageDialog(null, e); }
            finally { try { rs.close(); pst.close();}catch (Exception e){  } }
    }
    
    private void tbl_partnerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_partnerMouseClicked
        try{
            int row=tbl_partner.getSelectedRow();
            String Table_click=(tbl_partner.getModel().getValueAt(row, 0).toString());

            String sql="SELECT *  FROM partner WHERE partner.code_part ='"+Table_click+"'   ";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();

            if(rs.next()){
                String code_part =rs.getString("code_part"); txt_code_part.setText(code_part);
                String name_part =rs.getString("name_part"); txt_name_part.setText(name_part);
                String add_part =rs.getString("add_part"); txt_add_part.setText(add_part);
                String district_part =rs.getString("district_part"); txt_district_part.setText(district_part);
                String province_part =rs.getString("province_part"); txt_province_part.setText(province_part);
                String company_part =rs.getString("company_part"); txt_company_part.setText(company_part);
                String phone_part =rs.getString("phone_part"); txt_phone_part.setText(phone_part);
                String fax_part =rs.getString("fax_part"); txt_fax_part.setText(fax_part);
                String email_part =rs.getString("email_part"); txt_email_part.setText(email_part);
                String note_part =rs.getString("note_part"); txt_note_part.setText(note_part);
            }
        }catch(Exception e){ JOptionPane.showMessageDialog(null, e);}
        finally { try { rs.close(); pst.close();}catch (Exception e){  } }
    }//GEN-LAST:event_tbl_partnerMouseClicked

    private void cmd_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_closeActionPerformed
        try {rs.close();pst.close();dispose();}catch (Exception e){}
    }//GEN-LAST:event_cmd_closeActionPerformed

    private void cmd_addnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_addnewActionPerformed
        String sql = "SELECT * FROM partner ORDER BY code_part DESC LIMIT 1";
        try {
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            String mch = MCH();
            if(rs.next()){
                String code_part =rs.getString("code_part").substring(4);
                int code = Integer.parseInt(code_part);
                String code_up = Integer.toString(code+1);
                int n = 8 - 4 - code_up.length();
                String zero = new String(new char[n]).replace("\0", "0");
                String code_2 = "DT"+ mch+zero + code_up;
                txt_code_part.setText(code_2);
            }else{
                txt_code_part.setText("DT"+mch+"0001");
            }
        } catch (Exception e){ JOptionPane.showMessageDialog(null, e);}
        finally { try { rs.close(); pst.close();}catch (Exception e){  } }

        txt_name_part.setText("");
        txt_add_part.setText("");
        txt_district_part.setText("");
        txt_province_part.setText("");
        txt_company_part.setText("");
        txt_phone_part.setText("");
        txt_fax_part.setText("");
        txt_email_part.setText("");
        txt_note_part.setText("");
        txt_name_part.requestFocusInWindow();
    }//GEN-LAST:event_cmd_addnewActionPerformed

    private void cmd_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_saveActionPerformed
        try{
            String sql ="INSERT INTO partner (code_part, name_part, add_part, district_part, province_part, "
            + "company_part, phone_part, fax_part, email_part, note_part, user_part) values (?,?,?,?,?,?,?,?,?,?,?)";

            pst =conn.prepareStatement(sql);
            pst.setString(1, txt_code_part.getText());
            pst.setString(2, txt_name_part.getText());
            pst.setString(3, txt_add_part.getText());
            pst.setString(4, txt_district_part.getText());
            pst.setString(5, txt_province_part.getText());
            pst.setString(6, txt_company_part.getText());
            pst.setString(7, txt_phone_part.getText());
            pst.setString(8, txt_fax_part.getText());
            pst.setString(9, txt_email_part.getText());
            pst.setString(10, txt_note_part.getText());
            pst.setString(11, dashboard.lable_user.getText());
            pst.execute();

            JOptionPane.showMessageDialog(null, "Một thông tin đối tác mới vừa được thêm vào!");

        }catch(Exception e){JOptionPane.showMessageDialog(null, e);}
        finally {try {rs.close();pst.close();}catch (Exception e){}}

        Update_table_partner();
    }//GEN-LAST:event_cmd_saveActionPerformed

    private void cmd_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_deleteActionPerformed
        int p =JOptionPane.showConfirmDialog(null, "Bạn có muốn xóa dữ liệu khách hàng này không?", "Delete Class", JOptionPane.YES_NO_OPTION);
        if (p==0){
            try{
                String sql="DELETE FROM partner where code_part = ?";
                pst=conn.prepareStatement(sql);
                pst.setString(1, txt_code_part.getText());
                pst.execute();
            }catch(Exception e){JOptionPane.showMessageDialog(null, e);}
            finally {try {rs.close();pst.close();}catch (Exception e){}}
        }

        Update_table_partner();
    }//GEN-LAST:event_cmd_deleteActionPerformed

    private void cmd_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_updateActionPerformed
        try{
            String  code_part = txt_code_part.getText();
            String name_part = txt_name_part.getText();
            String add_part = txt_add_part.getText();
            String district_part = txt_district_part.getText();
            String province_part = txt_province_part.getText();
            String company_part = txt_company_part.getText();
            String phone_part = txt_phone_part.getText();
            String fax_part = txt_fax_part.getText();
            String email_part = txt_email_part.getText();
            String note_part = txt_note_part.getText();
            String user_part = dashboard.lable_user.getText();

            String sql ="UPDATE partner SET name_part = '"+name_part+"', add_part = '"+add_part+"', "
            + "district_part = '"+district_part+"', province_part = '"+province_part+"', company_part = '"+company_part+"', "
            + "phone_part = '"+phone_part+"' , fax_part = '"+fax_part+"', email_part = '"+email_part+"',"
                    + " note_part = '"+note_part+"', user_part = '"+user_part+"' WHERE code_part ='"+code_part+"'  ";
            pst=conn.prepareStatement(sql);
            pst.execute();

            JOptionPane.showMessageDialog(null, "Một thông tin đối tác vừa được cập nhật !");

        }catch(SQLException e){JOptionPane.showMessageDialog(null, e);} catch (HeadlessException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        finally {try {rs.close();pst.close();}catch (Exception e){}}

        Update_table_partner();
    }//GEN-LAST:event_cmd_updateActionPerformed

    private void cmd_mcloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_mcloseActionPerformed
        try {rs.close();pst.close();dispose();}catch (Exception e){}
    }//GEN-LAST:event_cmd_mcloseActionPerformed

    private void cmd_refreshtableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_refreshtableActionPerformed
        Update_table_partner();
    }//GEN-LAST:event_cmd_refreshtableActionPerformed

    private void menu_export_xlsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_export_xlsActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Export Partner to .xls file");
        int retval = chooser.showSaveDialog(null);
        File f = chooser.getSelectedFile();
        String outputDirPath=f.getAbsolutePath();

        if (retval==JFileChooser.APPROVE_OPTION){
            if(f.exists()) {
                int p =JOptionPane.showConfirmDialog(null, "File này đã có! Bạn có muốn ghi đè lên file này k?", "Over-write", JOptionPane.YES_NO_OPTION);
                if (p==1){
                return;
                }
            }

                Workbook wb = new HSSFWorkbook();
                Sheet personSheet = wb.createSheet("partner");
                //create font style
                HSSFFont font = (HSSFFont) wb.createFont();
                font.setColor(HSSFFont.COLOR_RED);
                font.setBoldweight(HSSFFont.BOLDWEIGHT_BOLD);
                font.setFontHeightInPoints((short) 24);
                HSSFCellStyle cellStyle= (HSSFCellStyle) wb.createCellStyle();
                cellStyle.setFont(font);
                //
                Row titlerow = personSheet.createRow(0);
                titlerow.setHeightInPoints((short) 26);
                Cell nametitle = titlerow.createCell(0);
                nametitle.setCellStyle(cellStyle);
                nametitle.setCellValue("Danh Sách Đối Tác");


                Row headerRow = personSheet.createRow(1);
                    Cell code_cust = headerRow.createCell(0); code_cust.setCellValue("Partner ID");
                    Cell name_cust = headerRow.createCell(1); name_cust.setCellValue("Partner Name");
                    Cell add_cust = headerRow.createCell(2); add_cust.setCellValue("Address");
                    Cell district_cust = headerRow.createCell(3); district_cust.setCellValue("District");
                    Cell province_cust = headerRow.createCell(4); province_cust.setCellValue("Province");
                    Cell company_cust = headerRow.createCell(5); company_cust.setCellValue("Company");
                    Cell phone_cust = headerRow.createCell(6); phone_cust.setCellValue("Phone");
                    Cell fax_cust = headerRow.createCell(7); fax_cust.setCellValue("Fax");
                    Cell email_cust = headerRow.createCell(8); email_cust.setCellValue("Email");
                    Cell note_cust = headerRow.createCell(9); note_cust.setCellValue("Note");

                try{
                String sql = "SELECT code_part, name_part, add_part, district_part, province_part, company_part, phone_part, fax_part, email_part, note_part"
                        + " FROM partner ORDER BY code_part ";
                pst=conn.prepareStatement(sql);
                rs=pst.executeQuery(); 

                int row = 2;
                while(rs.next()) {
                    Row dataRow = personSheet.createRow(row);

                    Cell code_custCell = dataRow.createCell(0);
                        code_custCell.setCellValue(rs.getString("code_part"));
                    Cell name_custCell = dataRow.createCell(1);
                        name_custCell.setCellValue(rs.getString("name_part"));
                    Cell add_custCell = dataRow.createCell(2);
                        add_custCell.setCellValue(rs.getString("add_part"));
                    Cell district_custCell = dataRow.createCell(3);
                        district_custCell.setCellValue(rs.getString("district_part"));
                    Cell province_custCell = dataRow.createCell(4);
                        province_custCell.setCellValue(rs.getString("province_part"));
                    Cell company_custCell = dataRow.createCell(5);
                        company_custCell.setCellValue(rs.getString("company_part"));
                    Cell phone_custCell = dataRow.createCell(6);
                        phone_custCell.setCellValue(rs.getString("phone_part"));
                    Cell fax_custCell = dataRow.createCell(7);
                        fax_custCell.setCellValue(rs.getString("fax_part"));
                    Cell email_custCell = dataRow.createCell(8);
                        email_custCell.setCellValue(rs.getString("email_part"));
                    Cell note_custCell = dataRow.createCell(9);
                        note_custCell.setCellValue(rs.getString("note_part"));

                    row = row + 1;
                }


                FileOutputStream fileOut = new FileOutputStream(outputDirPath);
                wb.write(fileOut);
                fileOut.close();
                JOptionPane.showMessageDialog(null, "Danh sách Đối tác đã được xuất tới " + outputDirPath);
                } catch(Exception e){JOptionPane.showMessageDialog(null, e);}
                finally { try { rs.close(); pst.close();}catch (Exception e){  } }
        }
    }//GEN-LAST:event_menu_export_xlsActionPerformed

    private void menu_export_csvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_export_csvActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Export table PARTNER to .csv file");
        int retval = chooser.showSaveDialog(null);
        File f = chooser.getSelectedFile();
        String outputDirPath=f.getAbsolutePath();

        if (retval==JFileChooser.APPROVE_OPTION){
        if(f.exists()) {
            int p =JOptionPane.showConfirmDialog(null, "File đã có! Bạn có muốn ghi đè lên file này?", "Over-write", JOptionPane.YES_NO_OPTION);
            if (p==1){
            return;
            }
        }
            try{
            FileWriter fw = new FileWriter(outputDirPath);
            String sql = " SELECT * FROM partner ORDER BY code_part ";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery(); 

            while(rs.next()) {
                fw.append('"'); fw.append(rs.getString("code_part")); fw.append('"'); fw.append(',');
                fw.append('"');fw.append(rs.getString("name_part"));fw.append('"'); fw.append(',');
                fw.append('"');fw.append(rs.getString("add_part"));fw.append('"'); fw.append(',');
                fw.append('"');fw.append(rs.getString("district_part"));fw.append('"'); fw.append(',');
                fw.append('"');fw.append(rs.getString("province_part"));fw.append('"'); fw.append(',');
                fw.append('"');fw.append(rs.getString("company_part"));fw.append('"'); fw.append(',');
                fw.append('"');fw.append(rs.getString("phone_part"));fw.append('"'); fw.append(',');
                fw.append('"');fw.append(rs.getString("fax_part"));fw.append('"'); fw.append(',');
                fw.append('"');fw.append(rs.getString("email_part"));fw.append('"'); fw.append(',');
                fw.append('"');fw.append(rs.getString("note_part"));fw.append('"'); fw.append(',');
                fw.append('"');fw.append(rs.getString("user_part"));fw.append('"'); fw.append('\n');
            }
            fw.flush();
            fw.close();
            
            JOptionPane.showMessageDialog(null, "Dữ liệu Đối tác đã được xuất tới " + outputDirPath);
            } catch(Exception e){JOptionPane.showMessageDialog(null, e);}
            finally {try {rs.close();pst.close();}catch (Exception e){}}
        
        }
    }//GEN-LAST:event_menu_export_csvActionPerformed

    private void menu_import_csvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_import_csvActionPerformed
        int p =JOptionPane.showConfirmDialog(null, "Bạn có muốn import danh sách Đối tác?", "Import Partner", JOptionPane.YES_NO_OPTION);
        if (p==0){
        try{
            JFileChooser chooser = new JFileChooser();
            chooser.showOpenDialog(null);
            File f = chooser.getSelectedFile();
            String filename1 = f.getAbsolutePath();
            
            BufferedReader br = new BufferedReader(new FileReader(filename1));
            String line;

            while((line = br.readLine())!=null){
                line = line.substring(1, line.length() - 1);
                line=line.replace("null", "");
                String[] value= line.split("\",\""); //seperator \",\"
                //System.out.println(value[1]);
                String sql = "INSERT INTO 'partner' (code_part, name_part, add_part, "
                        + "district_part, province_part, company_part, phone_part, "
                        + "fax_part, email_part, note_part, user_part) "
                        + "values ('"+value[0]+"', '"+value[1]+"', '"+value[2]+"', "
                        + "'"+value[3]+"', '"+value[4]+"', '"+value[5]+"', '"+value[6]+"', "
                        + "'"+value[7]+"', '"+value[8]+"', '"+value[9]+"', '"+value[10]+"')";
                pst=conn.prepareStatement(sql);
                pst.executeUpdate();
                this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            }
            br.close();
            this.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
        }catch(Exception e){JOptionPane.showMessageDialog(null, e);}
                finally {try {rs.close();pst.close();}catch (Exception e){}}
        }

        Update_table_partner();
    }//GEN-LAST:event_menu_import_csvActionPerformed

    private void menu_delete_allActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_delete_allActionPerformed
        int p =JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn xóa hết dữ liệu?", "Delete PARTNER", JOptionPane.YES_NO_OPTION);
        if (p==0){
        try{
            String sql="DELETE FROM partner";
            pst=conn.prepareStatement(sql);
            pst.execute();
        }catch(Exception e){JOptionPane.showMessageDialog(null, e);}
                finally {try {rs.close();pst.close();}catch (Exception e){}}
        }
        Update_table_partner();
    }//GEN-LAST:event_menu_delete_allActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(partner_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(partner_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(partner_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(partner_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new partner_frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmd_addnew;
    private javax.swing.JButton cmd_close;
    private javax.swing.JButton cmd_delete;
    private javax.swing.JMenuItem cmd_mclose;
    private javax.swing.JMenuItem cmd_refreshtable;
    private javax.swing.JButton cmd_save;
    private javax.swing.JButton cmd_update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem menu_delete_all;
    private javax.swing.JMenuItem menu_export_csv;
    private javax.swing.JMenuItem menu_export_xls;
    private javax.swing.JMenuItem menu_import_csv;
    private javax.swing.JTable tbl_partner;
    private javax.swing.JTextField txt_add_part;
    private javax.swing.JTextField txt_code_part;
    private javax.swing.JTextField txt_company_part;
    private javax.swing.JTextField txt_district_part;
    private javax.swing.JTextField txt_email_part;
    private javax.swing.JTextField txt_fax_part;
    private javax.swing.JTextField txt_name_part;
    private javax.swing.JTextField txt_note_part;
    private javax.swing.JTextField txt_phone_part;
    private javax.swing.JTextField txt_province_part;
    private javax.swing.JLabel txt_total_part;
    // End of variables declaration//GEN-END:variables
}
