/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author TrinhDang
 */
import java.awt.*;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import java.awt.print.*;
import java.io.*;
import java.sql.*;
import java.text.*;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import  java.util.logging.Logger;  
import javax.swing.*; 
import  net.proteanit.sql.DbUtils;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;


public class Employee_from extends javax.swing.JFrame {
    
    Connection conn=null;
    ResultSet rs =null;
    PreparedStatement pst =null;
    /**
     * Creates new form Employee_from
     */
public Employee_from() {
        initComponents();
        conn=javaconnect.ConnecrDb();
        Update_table();
        Fildcombo();
        CurrentDate();
        Fildtext();
    }

public void CurrentDate(){


Thread clock = new Thread(){
    public void run(){
        for(;;){
            
            Calendar cal =new GregorianCalendar();
            int month =cal.get(Calendar.MONTH);
            int year =cal.get(Calendar.YEAR);
            int day =cal.get(Calendar.DAY_OF_MONTH);
            date_txt.setText("Date"+year+"/"+(month+1)+"/"+day);

            int second =cal.get(Calendar.SECOND);
            int minute =cal.get(Calendar.MINUTE);
            int hour =cal.get(Calendar.HOUR);
            Time_txt.setText("Time"+hour+":"+(minute+1)+":"+second);
            
            System.out.println("p");
            try {
                sleep(1000);
            } catch (InterruptedException ex) {
                Logger.getLogger(Employee_from.class.getName()).log(Level.SEVERE, null, ex);
            }
            }
        }
    };
clock.start();
}

public void close(){
WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
}


private void Update_table(){
    try{
    String sql ="select id as 'ID', firstname as 'First Name', lastname as 'Last Name' from login";
    
    pst=conn.prepareStatement(sql);
    rs=pst.executeQuery();
    Table_Employee.setModel(DbUtils.resultSetToTableModel(rs));
            }
    catch (Exception e){
        JOptionPane.showMessageDialog(null, e);
        
    }
    finally {
    try {
        rs.close();
        pst.close();
        
    }catch (Exception e){
    }
}
} 


private void Fildcombo(){
    
try {
    String sql ="select * from login";
    pst=conn.prepareStatement(sql);
    rs=pst.executeQuery();
    ComboBox_name.addItem("");
    ComboBox_name.setEditable(true);
    while(rs.next()){
        String name =rs.getString("lastname");
        ComboBox_name.addItem(name);}
        AutoCompleteDecorator.decorate(this.ComboBox_name);
    }
    catch (Exception e){JOptionPane.showMessageDialog(null, e);}
    finally {try {rs.close();pst.close();}catch (Exception e){}}


}

private void Fildtext(){
        //ArrayList<String> stock_list = new ArrayList<String>();
        //try{
            //String sql = " SELECT lastname FROM 'login' ORDER BY lastname ";
           // pst=conn.prepareStatement(sql); rs=pst.executeQuery(); 
          // while(rs.next()) {stock_list.add(rs.getString("lastname"));}rs.close();
        //} catch(Exception e){JOptionPane.showMessageDialog(null, e);} finally {try {rs.close();pst.close();}catch (Exception e){}}
        //String[]splist = stock_list.toArray(new String[stock_list.size()]);
        
        //AutoCompleteDecorator.decorate(splist, this.txt_field1);
    
    String[] myStrings = new String[] {"Elem1","Elem2","Elem3","Elem4","Elem5"};

    JList list = new JList(myStrings); //data has type Object[]
    AutoCompleteDecorator.decorate(list, this.txt_field1);

}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Table_Employee = new javax.swing.JTable();
        ComboBox_name = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        txt_name = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txt_surname = new javax.swing.JTextField();
        txt_id = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Cmd_save = new javax.swing.JButton();
        cmd_delete = new javax.swing.JButton();
        cmd_clear = new javax.swing.JButton();
        txt_update = new javax.swing.JButton();
        cmd_print = new javax.swing.JButton();
        New_frame = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txt_search = new javax.swing.JTextField();
        cmd_export = new javax.swing.JButton();
        txt_field1 = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        txt_exit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        date_txt = new javax.swing.JMenu();
        Time_txt = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        Table_Employee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Table_Employee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_EmployeeMouseClicked(evt);
            }
        });
        Table_Employee.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Table_EmployeeKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Table_EmployeeKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(Table_Employee);

        ComboBox_name.setEditable(true);
        ComboBox_name.setToolTipText("");
        ComboBox_name.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                ComboBox_namePopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        ComboBox_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ComboBox_nameKeyReleased(evt);
            }
        });

        jLabel1.setText("Id");

        jLabel3.setText("Surname");

        jLabel2.setText("Name");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_surname)
                    .addComponent(txt_name)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_surname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        Cmd_save.setText("SAVE");
        Cmd_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cmd_saveActionPerformed(evt);
            }
        });

        cmd_delete.setText("Delete");
        cmd_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_deleteActionPerformed(evt);
            }
        });

        cmd_clear.setText("Clear");
        cmd_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_clearActionPerformed(evt);
            }
        });

        txt_update.setText("Update");
        txt_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_updateActionPerformed(evt);
            }
        });

        cmd_print.setText("Print");
        cmd_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_printActionPerformed(evt);
            }
        });

        New_frame.setText("Count frame");
        New_frame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                New_frameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Cmd_save, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmd_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_update)
                    .addComponent(cmd_clear)
                    .addComponent(cmd_print))
                .addContainerGap())
            .addComponent(New_frame, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Cmd_save, cmd_clear, cmd_delete, txt_update});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Cmd_save)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmd_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_update, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmd_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmd_print)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(New_frame)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Cmd_save, cmd_clear, cmd_delete, txt_update});

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(51, 51, 255))); // NOI18N

        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        cmd_export.setText("Export to .els");
        cmd_export.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_exportActionPerformed(evt);
            }
        });

        txt_field1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_field1KeyReleased(evt);
            }
        });

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("New");
        jMenu1.add(jMenuItem1);
        jMenu1.add(jSeparator1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Close");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        txt_exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        txt_exit.setText("Exit");
        txt_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_exitActionPerformed(evt);
            }
        });
        jMenu1.add(txt_exit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Help");

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Help file");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("     ");
        jMenu4.setMaximumSize(new java.awt.Dimension(187, 32767));
        jMenuBar1.add(jMenu4);

        date_txt.setText("Date");
        jMenuBar1.add(date_txt);

        Time_txt.setText("Time");
        jMenuBar1.add(Time_txt);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmd_export)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ComboBox_name, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_field1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ComboBox_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmd_export))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(txt_field1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(581, 488));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        // TODO add your handling code here:        
    }//GEN-LAST:event_jScrollPane1MouseClicked


//Table Click
    private void Table_EmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_EmployeeMouseClicked
        // TODO add your handling code here:
        try{
        int row=Table_Employee.getSelectedRow();
        String Table_click=(Table_Employee.getModel().getValueAt(row, 0).toString());
            
            String sql="select * from login where id ='"+Table_click+"'   ";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            
            if(rs.next()){
                
                String add1 =rs.getString("id");
                txt_id.setText(add1);
                String add2 =rs.getString("firstname");
                txt_name.setText(add2);
                String add3 =rs.getString("lastname");
                txt_surname.setText(add3);
                ComboBox_name.setSelectedItem(add3);
            }
        }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
            }
                finally {
                    try {
                        rs.close();
                        pst.close();

                    }catch (Exception e){
                    }
                    }
        
    }//GEN-LAST:event_Table_EmployeeMouseClicked


//ComboBox search
    private void ComboBox_namePopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_ComboBox_namePopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        String tmp =(String)ComboBox_name.getSelectedItem();
        String sql="select * from login where lastname =?";
        try{
        pst=conn.prepareStatement(sql);
        pst.setString(1, tmp);
        rs=pst.executeQuery();
        
        if(rs.next()){
            String add1 =rs.getString("id");
            txt_id.setText(add1);
            String add2 =rs.getString("firstname");
            txt_name.setText(add2);
            String add3 =rs.getString("lastname");
            txt_surname.setText(add3);
        }
            
        }catch(Exception e){JOptionPane.showMessageDialog(null, e);}
                finally {try {rs.close();pst.close();}catch (Exception e){}}
        
        
    }//GEN-LAST:event_ComboBox_namePopupMenuWillBecomeInvisible


//close manu
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        close();
        
        
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed


//Save data
    private void Cmd_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cmd_saveActionPerformed
        // TODO add your handling code here:
        try{
        String sql ="Insert into login (id, firstname, lastname) values (?,?,?)";
        
        pst =conn.prepareStatement(sql);
        pst.setString(1, txt_id.getText());
        pst.setString(2,txt_name.getText());
        pst.setString(3, txt_surname.getText());
        pst.execute();
        
        JOptionPane.showMessageDialog(null, "Saved");
        
        
        }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
            }
        finally {
                    try {
                        rs.close();
                        pst.close();

                    }catch (Exception e){
                    }
                    }
        Update_table();
    }//GEN-LAST:event_Cmd_saveActionPerformed

    private void New_frameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_New_frameActionPerformed
        // TODO add your handling code here:
        try{
        close();
        
        Userino_frame s =new Userino_frame();
        s.setVisible(true);
        } catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
            }
        
        finally {
        try {
        rs.close();
        pst.close();
        
            }catch (Exception e){
            }
        }
    }//GEN-LAST:event_New_frameActionPerformed

//delete data
    private void cmd_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_deleteActionPerformed
        int p =JOptionPane.showConfirmDialog(null, "Do you want to DELETE this data?", "Delete", JOptionPane.YES_NO_OPTION);
        if (p==0){
        String sql="delete from login where id = ?";
        try{
        
            pst=conn.prepareStatement(sql);
            pst.setString(1, txt_id.getText());
            
            pst.execute();
        
            //JOptionPane.showMessageDialog(null, "Deleted");
        
        }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
            }
                finally {
                    try {
                        rs.close();
                        pst.close();

                    }catch (Exception e){
                    }
                    }
        Update_table();
        }
    }//GEN-LAST:event_cmd_deleteActionPerformed

    
//update data    
    private void txt_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_updateActionPerformed
        
        try{
            String value1=txt_id.getText();
            String value2 =txt_name.getText();
            String value3 =txt_surname.getText();
            
            String sql ="update login set id ='"+value1+"', firstname ='"+value2+"', lastname='"+value3+"' where id ='"+value1+"'  ";
            pst=conn.prepareStatement(sql);
            pst.execute();
        
            JOptionPane.showMessageDialog(null, "Updated");
        
        }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
            }
                finally {
                    try {
                        rs.close();
                        pst.close();

                    }catch (Exception e){
                    }
                    }
        Update_table();
        
    }//GEN-LAST:event_txt_updateActionPerformed

// Clear Field
    private void cmd_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_clearActionPerformed
        txt_id.setText("");
        txt_name.setText("");
        txt_surname.setText("");
    }//GEN-LAST:event_cmd_clearActionPerformed

    
    
//Search Code
    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased
        try{
        String sql ="select * from login where firstname =?";
        
        pst=conn.prepareStatement(sql);
        pst.setString(1, txt_search.getText());
        
        rs=pst.executeQuery();
        if(rs.next()){
            String add1 =rs.getString("id");
            txt_id.setText(add1);
            String add2 =rs.getString("firstname");
            txt_name.setText(add2);
            String add3 =rs.getString("lastname");
            txt_surname.setText(add3);
            
            }
        }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
            }
        
        try{
        String sql ="select * from login where id =?";
        
        pst=conn.prepareStatement(sql);
        pst.setString(1, txt_search.getText());
        
        rs=pst.executeQuery();
        if(rs.next()){
            String add1 =rs.getString("id");
            txt_id.setText(add1);
            String add2 =rs.getString("firstname");
            txt_name.setText(add2);
            String add3 =rs.getString("lastname");
            txt_surname.setText(add3);
            
            }
        }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
            }
        
        try{
        String sql ="select * from login where lastname =?";
        
        pst=conn.prepareStatement(sql);
        pst.setString(1, txt_search.getText());
        
        rs=pst.executeQuery();
        if(rs.next()){
            String add1 =rs.getString("id");
            txt_id.setText(add1);
            String add2 =rs.getString("firstname");
            txt_name.setText(add2);
            String add3 =rs.getString("lastname");
            txt_surname.setText(add3);
            
            }
        }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
            }
            finally {
                    try {
                        rs.close();
                        pst.close();

                    }catch (Exception e){
                    }
                    }
        
    }//GEN-LAST:event_txt_searchKeyReleased

    private void Table_EmployeeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Table_EmployeeKeyPressed
     
        
    }//GEN-LAST:event_Table_EmployeeKeyPressed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        try{
        Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler "+"C:\\Users\\TrinhDang\\Downloads\\Thesis Proposal.pdf");
        
        }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
            }
            
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void txt_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_exitActionPerformed
       System.exit(0);
        
    }//GEN-LAST:event_txt_exitActionPerformed

    private void cmd_printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_printActionPerformed
        MessageFormat header = new MessageFormat("Report Print");
        MessageFormat footer = new MessageFormat("Page{0, number, integer}");
        try{
        
            Table_Employee.print(JTable.PrintMode.NORMAL,header, footer);
            
        }catch(java.awt.print.PrinterException e){
        System.err.format("Cannot print %s%n", e.getMessage());
            }
    }//GEN-LAST:event_cmd_printActionPerformed

    private void Table_EmployeeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Table_EmployeeKeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_DOWN || evt.getKeyCode()==KeyEvent.VK_UP){
        
        try{
        int row=Table_Employee.getSelectedRow();
        String Table_click=(Table_Employee.getModel().getValueAt(row, 0).toString());
            
            String sql="select * from login where id ='"+Table_click+"'   ";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            
            if(rs.next()){
                
                String add1 =rs.getString("id");
                txt_id.setText(add1);
                String add2 =rs.getString("firstname");
                txt_name.setText(add2);
                String add3 =rs.getString("lastname");
                txt_surname.setText(add3);
            }
        }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
            }
        
        }
    }//GEN-LAST:event_Table_EmployeeKeyReleased

    private void cmd_exportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_exportActionPerformed
        Workbook wb = new HSSFWorkbook();
        Sheet personSheet = wb.createSheet("Login");
        
        Row titlerow = personSheet.createRow(0);
        Cell nametitle = titlerow.createCell(0);
        nametitle.setCellValue("AN THAI PHU");
        
        Row headerRow = personSheet.createRow(1);
        Cell nameHeaderCell = headerRow.createCell(0);
        Cell addressHeaderCell = headerRow.createCell(1);
        nameHeaderCell.setCellValue("First Name");
        addressHeaderCell.setCellValue("Last Name");
try{
        String sql = "select firstname, lastname from login";
        pst=conn.prepareStatement(sql);
        rs=pst.executeQuery(); 

        int row = 2;
        while(rs.next()) {
            String name = rs.getString("firstname");
            String address = rs.getString("lastname");

            Row dataRow = personSheet.createRow(row);

            Cell dataNameCell = dataRow.createCell(0);
            dataNameCell.setCellValue(name);

            Cell dataAddressCell = dataRow.createCell(1);
            dataAddressCell.setCellValue(address);

            row = row + 1;
        }

        String outputDirPath = "/home/trinhdangmau/Documents/PersonList.xls";
        FileOutputStream fileOut = new FileOutputStream(outputDirPath);
        wb.write(fileOut);
        fileOut.close();
        JOptionPane.showMessageDialog(null, "Your excel file has been generated!");
} catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
            }
    }//GEN-LAST:event_cmd_exportActionPerformed

    private void ComboBox_nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ComboBox_nameKeyReleased
        
    }//GEN-LAST:event_ComboBox_nameKeyReleased

    private void txt_field1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_field1KeyReleased
        
    }//GEN-LAST:event_txt_field1KeyReleased

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employee_from.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employee_from.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employee_from.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employee_from.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employee_from().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cmd_save;
    private javax.swing.JComboBox ComboBox_name;
    private javax.swing.JButton New_frame;
    private javax.swing.JTable Table_Employee;
    private javax.swing.JMenu Time_txt;
    private javax.swing.JButton cmd_clear;
    private javax.swing.JButton cmd_delete;
    private javax.swing.JButton cmd_export;
    private javax.swing.JButton cmd_print;
    private javax.swing.JMenu date_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem txt_exit;
    private javax.swing.JTextField txt_field1;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_search;
    private javax.swing.JTextField txt_surname;
    private javax.swing.JButton txt_update;
    // End of variables declaration//GEN-END:variables
}
